// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5nYgxdR4votqLM-Zt_W0un8ay8ELV0I',
    appId: '1:996298497923:web:76e7696a46d2c0fb42a0b6',
    messagingSenderId: '996298497923',
    projectId: 'flutterbank-f83c6',
    authDomain: 'flutterbank-f83c6.firebaseapp.com',
    storageBucket: 'flutterbank-f83c6.firebasestorage.app',
    measurementId: 'G-WH42JHZ0EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA646nWiizD7jcV5CaGxXhR-jY-bpHIHv8',
    appId: '1:996298497923:android:48570f6b2f5e032842a0b6',
    messagingSenderId: '996298497923',
    projectId: 'flutterbank-f83c6',
    storageBucket: 'flutterbank-f83c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQl0S5w4WsbR9J3RHV6MKyix1qcV5xoJ0',
    appId: '1:996298497923:ios:7acfa137ff99869c42a0b6',
    messagingSenderId: '996298497923',
    projectId: 'flutterbank-f83c6',
    storageBucket: 'flutterbank-f83c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQl0S5w4WsbR9J3RHV6MKyix1qcV5xoJ0',
    appId: '1:996298497923:ios:7acfa137ff99869c42a0b6',
    messagingSenderId: '996298497923',
    projectId: 'flutterbank-f83c6',
    storageBucket: 'flutterbank-f83c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5nYgxdR4votqLM-Zt_W0un8ay8ELV0I',
    appId: '1:996298497923:web:cdf92482941dbc9f42a0b6',
    messagingSenderId: '996298497923',
    projectId: 'flutterbank-f83c6',
    authDomain: 'flutterbank-f83c6.firebaseapp.com',
    storageBucket: 'flutterbank-f83c6.firebasestorage.app',
    measurementId: 'G-T07VRTZ9FJ',
  );

}